### ISSUE TITLE
TypeError: u.valToPos is not a function

### ISSUE THREAD

**Issue by Feduch** [skalinichev/uplot-wrappers#1]
Hi!

Thanks for uplot-wrappers!

I want create gradient line, where line color related from value. 

Example from there are https://leeoniya.github.io/uPlot/demos/gradient-stroke.html

I get an error: TypeError: u.valToPos is not a function

My code:

```
options: {
        id: "wb-chart-content",
        height: 330,
        legend: {
          show: false
        },
        series: [
          {},
          {
            label: "Temperature",
            width: 1,
            // series style
            stroke: (u, seriesIdx) => {
              console.log(u)

              return this.scaleGradient(u, 'y', 1, [
                [0, "#0ACEF9"],
                [46, "#FFE663"],
                [60, "#F9440A"],
              ])
            },
          },
        ],
        axes: [
          {show: false,},
          {show: false}
        ]
      }
```

```
methods: {
    onCreate(event) {
      console.log("onCreate", event)
      event.setSize(this.getSize())
    },
    onDelete(event) {
      console.log("onDelete", event)
    },
    scaleGradient(u, scaleKey, ori, scaleStops) {
      console.log(u, scaleKey, ori, scaleStops)

      let min = scaleStops[0][0];
      let max = scaleStops[scaleStops.length - 1][0];
      let rng = max - min;

      let minPos = u.valToPos(min, scaleKey, true);
      let maxPos = u.valToPos(max, scaleKey, true);

      let x0, y0, x1, y1;

      if (ori == 1) {
        x0 = x1 = 0;
        y0 = minPos;
        y1 = maxPos;
      }
      else {
        y0 = y1 = 0;
        x0 = minPos;
        x1 = maxPos;
      }

      let grd = u.ctx.createLinearGradient(x0, y0, x1, y1);

      scaleStops.forEach(s => {
        let pct = (s[0] - min) / rng;
        grd.addColorStop(pct, s[1]);
      });

      return grd;
    }
  },
```

**Comment by skalinichev** [comment]
Seems like the bug is inside uPlot itself. It invokes stroke functions for 'cursor.points' and 'legend' too earlier w/o initializing some of it's inner properties. I'll see what we can do about it.

As a temporarily w/a you can override legend.stroke and cursor.points.stroke functions as in the gradient example [https://leeoniya.github.io/uPlot/demos/gradient-stroke.html](https://leeoniya.github.io/uPlot/demos/gradient-stroke.html)

**Comment by leeoniya** [comment]
if you're using canvas gradients for series fill or series stroke, you _have_ to override the corresponding properties in `legend` and `cursor.points` because those interactive elements are in the DOM and they cannot consume (or inherit) a canvas gradient. so overriding these options is not just a temporary fix, it has to be done.

that being said, if a crash can be avoided, it should be, but that will just push the error downstream to where the dom element's css styles fail to parse the canvas gradient object.

**Comment by skalinichev** [comment]
The missing instance properties issue got merged upstream.

Closing as per @leeoniya explanation.
