### ISSUE TITLE
Not detecting new hooks in options

### ISSUE THREAD

**Issue by ivankhm** [skalinichev/uplot-wrappers#13]
Hello! I faced an issue: when I update one of the functions passed to options.hook - changes not detected and wrapper using old options, because this utill comparing functions by stringifying them. 
https://github.com/skalinichev/uplot-wrappers/blob/26788ea6d041cb95daa38f4892783f39756ff25d/common/index.ts#L22

For example, we have component:
``` typescript

const MyCoolChart = (someFunction: (value: number) => string, data: uPlot.AlignedData) => {
  const drawAxesHook = (self: uPlot) => {
    console.log(someFunction(123))
  };

  const options = {
    //some options...
    hooks: [drawAxesHook]
  };
  
  return (<UplotReact data={data} options={options} />);
}
```

And in parent component we have:
```typescript
const [data, setData] = useState<uPlot.AlignedData>([[]]); //data can change
const someFunction = (value: number) => `formatting one ${value}`;

return (<MyCoolChart data={data} someFunction={someFunction} />);
```

On the first mount we will get in console: `formatting one 123`, which is correct. But if we somehow change someFunction, for example to:

```typescript
const someFunction = (value: number) => `formatting two ${value}`;
```
And then we mutate `data` by calling `setData`, we will get the same console.log:  `formatting one 123`, which is incorrect!

It compares functions as strings, and `stringify getting the same results, even though someFunction is changed. 

I purpose to use `Object.is` to compare to option fields:

```javascript
    if (!Object.is(lhs[k], rhs[k])) {
```

Or use polyfill, like in react source code: 

https://github.com/facebook/react/blob/4ce89a58dac5287a2c7fc454e86562297e97a6d9/packages/shared/objectIs.js#L14

If you want to perform deep equal - I purpose to use `lodash.isEqual`. Its quite fast, and if imported correctly, a single-function weight almost nothing https://www.measurethat.net/Benchmarks/Show/3940/0/fastdeepequal---lodashisequal

**Comment by skalinichev** [comment]
Yeah, I was afraid something of the sort would happen, thanks for the in-depth analysis!

The idea was to reduce uPlot instance re-creations if options didn't change, since it's a very costly operation and also visible to the end user. Though I agree, it's very difficult (if possible at all) to implement such optimization on the library side, seems like it should be done on the client side after all. Let's just drop this optimization altogether and compare by value instead, since the library user should know better when/if it needs to optimize additional uPlot re-renders.

**Comment by ivankhm** [comment]
Thank you for the fast feedback! 

I think there is a way to do some optimization on this step, I'll give it a thought, and maybe pr in the future
