### ISSUE TITLE
Css con't be use in UplotReact component 

### ISSUE THREAD

**Issue by hxse** [skalinichev/uplot-wrappers#16]
Code Like:
```
import UplotReact from "uplot-react";
function hello() {
  return <div style={{ display: "none" }}>hello world</div>; // CSS is running
  return <UplotReact options={options_} data={data_} style={{ display: "none" }} />; //CSS is not running
```
The display argument would work if it were a common react component but the UplotReact component does not.

**Comment by skalinichev** [comment]
Yes, it's not supported, but there are a lot of other ways to achieve the same result:
1. You can return null from render:
```javascript
    return shouldDisplay ? <UplotReact/> : null;
```
2. Or use a simple wrapper:
```javascript
    return <div style={{display: "none"}}><UplotReact/></div>
```
3. Or pass the target div with your styles applied to uplot:
```javascript
    return <UplotReact target={refToYourDivWithSlyles}/>;
```
4. If you need to fine-tune uplot styles even further you can always override the styles directly, their names are not minified.

Also, please, note that since uplot supports creating a plot instance on a target div element or even through a init function (see [the documentation about the target property](https://github.com/skalinichev/uplot-wrappers#documentation)), it's not quite clear to me how we should apply the styles in that case, since the top node may not even be available from inside the library.

So it's a won't fix I'm afraid, please, try using one of the solutions listed above instead.
