### ISSUE TITLE
React hook: Dynamically resizing plot according to window size

### ISSUE THREAD

**Issue by kironsen** [skalinichev/uplot-wrappers#23]
Hi there, thank you for making this helpful library :) I'm trying to dynamically resize the plot to half the window size using flexboxes, `useRef() -> clientWidth/Height`, and React effects/callbacks.

I have an example here: https://codesandbox.io/s/uplot-react-resizing-3m733r. Current issues:
- Resizing the window in any direction always increases `clientHeight`
- Widening the window increases `clientWidth` but narrowing the window does nothing

Sample logs from narrowing the window size:

> width = 695, height = 244 
width = 695, height = 301 
width = 695, height = 358 
width = 695, height = 415 
width = 695, height = 472 
width = 695, height = 529 
width = 695, height = 586 
width = 695, height = 643 
width = 695, height = 700 
width = 695, height = 757 
width = 695, height = 814 

I'm defining `target` as my local `ref.current as HTMLDivElement` so that I can create my own div with its own ref (instead this being done automatically: https://github.com/skalinichev/uplot-wrappers/blob/master/react/uplot-react.tsx#L81).

I couldn't find any resizing examples this repo but [the main repo has a resize demo](https://github.com/leeoniya/uPlot/blob/master/demos/resize.html). This example directly calls `setSize()` which is what I'm trying to do through updating `options`: https://github.com/skalinichev/uplot-wrappers/blob/master/react/uplot-react.tsx#L54.

Do you know what I'm doing wrong? Apologies if I'm missing something obvious, I'm totally new to web dev.

Note: this example needs some fixing so that it resizes on startup as well.

**Comment by skalinichev** [comment]
Hi

Well, the problem is that you're trying to use the exact same DOM node for uplot and for retrieving clientWidth/clientHeight calculations. When one uses uplot.setWidth/setHeight, uplot modifies it's node's width/height. Therefore upon resizing clientWidth/clientHeight contain the exact same values uplot set for them.
The uplot example https://github.com/leeoniya/uPlot/blob/master/demos/resize.html doesn't use the exact same DOM node, it uses window.innerWidth/innerHeight instead.
To solve this problem you need to either also use window.innerWidth/innerHeight or 2 different DOM nodes: one is a wrapper that handles clientWidth/clientHeight, another one is the node for uplot.
See the code snippet below:
  ```
<div ref={wrapperRef} style={{width: '100%', height: '100%'}}>
    <div ref={plotRef}>
      <UplotReact
        options={options}
        data={data}
        target={plotRef.current as HTMLDivElement}
      />
    </div>
  </div>
  ...
  const handleResize = useCallback(() => {
    if (wrapperRef.current) {
      const newOptions = {
        ...options,
        title: "Resized",
        width: wrapperRef.current.clientWidth,
        height: wrapperRef.current.clientHeight
      };
      setOptions(newOptions);
    }
  }, [wrapperRef]);
```
