### ISSUE TITLE
Include ESM build in package.

### ISSUE THREAD

**Issue by ngbrown** [skalinichev/uplot-wrappers#27]
I am building a project with esbuild, and the rest of the code and most of the libraries support module mode. Even the ones that are CJS are imported and work correctly except for `uplot-react`.

I get the following error when building with it:

```
/home/node/app-dev/node_modules/uplot-react/webpack:/UplotReact/webpack/universalModuleDefinition:10
})(self, (__WEBPACK_EXTERNAL_MODULE_react__, __WEBPACK_EXTERNAL_MODULE_uplot__) => {
 ^
ReferenceError: self is not defined
    at Object.<anonymous> (/home/node/app-dev/node_modules/uplot-react/webpack:/UplotReact/webpack/universalModuleDefinition:10:2)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

Something is wrong with how webpack and esbuild are interfacing. I think ideally, an ESM specific build is also generated and that is included as a second import in the `package.json`.

**Comment by skalinichev** [comment]
I see. Will add the ESM build to the package then. Hopefully it will resolve the issue.

**Comment by ngbrown** [comment]
I also resolved the eslint errors in your `uplot-react.tsx` file. The caller is expected to pass stable `onDelete` and `onCreate` properties, possibly using `useCallback` if necessary.

https://gist.github.com/ngbrown/f8bb039cacc56f65a5424d6577866b80

Maybe you can incorporate this into your next release.

**Comment by skalinichev** [comment]
Yes, indeed. Thanks for spotting it!
Could you create a pull-request for it? I can also copy-paste the fix and mention you in the commit message if you prefer it that way.

**Comment by skalinichev** [comment]
Also I have pushed some changes that should hopefully resolve the issue with esbuild.
Adding an ESM build turned out to be problematic since it looks like webpack doesn't fully support it yet (I could also be doing something terribly wrong though...) Adding rollup, etc for it also seems like an overkill for me. So I have just changed 'self' to 'this' in the bundle, which should hopefully resolve the issue.

You can build it with 'yarn buildReact' or just replace 'self' with 'this' in the bundle. Please, check it and let me know if it works for you.

**Comment by ngbrown** [comment]
> Could you create a pull-request for it? I can also copy-paste the fix and mention you in the commit message if you prefer it that way.

You copy-pasting is fine so you can do your own testing and tweaks is fine.

The reason for the exports at the bottom is that I was having problems importing the enumeration with isolated modules enabled. I don't know that you need to keep that as it isn't your issue.

**Comment by skalinichev** [comment]
Done. I mostly pushed you patch as is. Just added some minor performance optimizations and removed className since it's IMO a bit counter-intuitive when used with the target element. Or maybe it's ok, we just need to mention it in the docs, I am not sure yet...
Anyway thanks for the patch! Will try to release it tomorrow.

**Comment by ngbrown** [comment]
@skalinichev The new version builds fine with esbuild in module/esm mode. Thanks for your library.
