### ISSUE TITLE
SUGGESTION: Svelte wrapper?

### ISSUE THREAD

**Issue by Zakrok09** [skalinichev/uplot-wrappers#29]
With Svelte's popularity and use in many contexts - e.g. native app development, web development etc, are there any plans to expand the uplot wrappers to encompass Svelte? 

### Motivation
I am currently developing an app in Tauri and stumbled upon uPlot. It was the perfect solution to my problem since I need to display plotted information in 200hz on the screen - something with uPlot deals with very well. I began abstracting graphs and plots into components and thought about whether there is already a wrapper about it.

P.S.
I am willing to write a wrapper inspired by the existing ones in Vue and React.

**Comment by Zakrok09** [comment]
Hello,

This is amazing, I am glad you find it interesting. I will fork the repo and add the `.svelte` components with their configuration. If possible you can assign me to the issue. 

P.S.
Would it be okay if I additionally add another component that takes care of auto-resizing? 
Also are there any outside requirements or considerations I should keep in mind? Thanks!

**Comment by skalinichev** [comment]
As for the requirements - just keep it simple, it should be a thin wrapper w/o extra functionality. Therefore adding an auto-resize component may be not such a good idea, since we can already pass chart width and height over props.
Also the component must have the exact same interface as the one written in React (i.e. accepts the same props). Also there is a common code in uplot-wrappers-common directory that can be reused. Generally just see how it's done in uplot-react.tsx, I imagine the functionality should be pretty much the same.

**Comment by Zakrok09** [comment]
Understood! This shouldn't take a lot of time. On it.
