### ISSUE TITLE
React wrapper `<div>` prevents full styling

### ISSUE THREAD

**Issue by jaens** [skalinichev/uplot-wrappers#33]
The `Uplot` React component by default creates an unstyleable wrapper `<div>` around the actual chart `<div>`.  (when the `target` property is unset)

![image](https://github.com/skalinichev/uplot-wrappers/assets/639345/391c98b3-727f-4723-8dae-a6648ede628a)

https://github.com/skalinichev/uplot-wrappers/blob/4242daf1f1135df540c701598dae780f81f5824e/react/uplot-react.tsx#L102

This always has `display: block`, so it does not work nicely as an inline element, unless using CSS selector hacks such as `> div` to style it from the parent. (which requires adding *another* wrapper `div`...)

The created `div` should probably inherit props from the `Uplot` component to make it styleable?

**Comment by skalinichev** [comment]
Yeah, actually this question was raised quite often recently. At first I though it was counter-intuitive, since there is already the target prop, which doesn't really work with the className prop.
After a bit more thinking though it doesn't seem to be such a big issue at all. Will add a className prop shortly, thanks for reminding me about it!
